services:
  api:
    build: .
    container_name: api_container
    restart: always
    environment:
      # Essas vari√°veis o Spring Boot reconhece automaticamente para configurar o DataSource
      SPRING_DATASOURCE_URL: jdbc:postgresql://31.97.163.104:5438/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: YvMTbK4AJJ9vXGxGqSatdE5fYXDe1X5PqzsrmAzXujgd4PM9vegnkoIq4wdBreSh
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8090:8080"
    networks:
      - local-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200m"

networks:
  local-network:
    driver: bridge
